version: "3.8"
services:
  directus:
    image: directus/directus
    ports:
      - 8055:8055
    environment:
      KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
      SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263
      ADMIN_EMAIL: "admin@admin.com"
      ADMIN_PASSWORD: "admin"
  frontend:
    build: static-client
    ports:
      - 3000:3000
    environment:
      DIRECTUS_CONNECTION_STRING: http://directus:8055
      CARS_COLLECTION_NAME: cars
    depends_on:
      - directus